### ISSUE TITLE
GUI-Device connected 

### ISSUE THREAD

**Issue by Hypnozk** [TactileVision/TactJam-client#1]
The client has to display if there are at the moment a device connected or not. If not a reconnect has to be possible. If the app is started, the first page has to be that a device have to be connected with a refresh button.

**Comment by bfrucha** [comment]
Implemented a serial connection feature. Need to update the state with the GUI.

**Comment by bfrucha** [comment]
Panel updates on device connection and disconnection + connection is read as the application opens.
