### ISSUE TITLE
Hide Login/Register

### ISSUE THREAD

**Issue by freitaggeorg** [TactileVision/TactJam-client#18]
Hide login area for easier use

**Comment by bfrucha** [comment]
Not sure what you mean. You would prefer not having a button "login"?

**Comment by freitaggeorg** [comment]
I do not want to have a login for the workshop. The application should start and be directly in the mode where I can record and display tactons. If a login should be necessary for the server, then it would have to be stored in the application. But the user should not have to register or log in in the current version.

**Comment by bfrucha** [comment]
I agree, but this was designed otherwise and it's unclear whether we can skip this step now. Maybe someone else has a solution to this.
