### ISSUE TITLE
Submit Bug

### ISSUE THREAD

**Issue by freitaggeorg** [TactileVision/TactJam-client#23]
The upload of the tacton is not executed when the submit button is pressed.If it is executed (there is no feedback), the application remains in the submit state and does not return to the initial screen.

**Comment by bfrucha** [comment]
Is there something appearing in the console? Uploading works on my side.

**Comment by freitaggeorg** [comment]
unfortunately i can't reproduce the bug. Currently it works. I remain attentive ;)
