### ISSUE TITLE
Upload errors

### ISSUE THREAD

**Issue by derikon** [TactileVision/TactJam-client#32]
# Test 1
I created a tacton and attached some actuators in the GUI. I tried several combinations to fill the form.
The submission form seems to have some bugs or at least is not so user friendly in terms of feedback.

## Only tacton name
string: "test_04_23_001"
result: 🛑  error `POST https://itactjam.informatik.htw-dresden.de/tactons/combined 400` from `saveLayout.tsx`

string: "test"
result:  ✅ 

string: "test 04 23 001"
result:  ✅ 

conclusion & suggestion:
- validate string before sending to avoid exceptions
- handle exceptions
- provide hints which characters are not allowed

# Test 2
I created **no** tacton and attached **no** actuators in the GUI.

result: ✅ which I would say is actually an error

conclusion & suggestion:
- check if anything meaningful is set, e.g. tacton and/or actuator placements

**Comment by bfrucha** [comment]
This was a discrepancy between the allowed characters in the GUI and what the server accepts.
